# Generated by Django 5.2.4 on 2025-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
