# Generated by Django 5.2.4 on 2025-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_purchaseorder_expected_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
