# Generated by Django 5.2.4 on 2025-08-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_date'], 'verbose_name': 'Purchase Orders', 'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
